from __future__ import annotations


DIFFICULTY_WEIGHT_MAP = {
    "easy": 1.0,
    "medium": 1.2,
    "hard": 1.5,
}


def build_question(
    order_no: int,
    category: str,
    difficulty: str,
    prompt: str,
    options: list[str],
    correct_option: str,
    explanation: str,
    tags: list[str],
    estimated_seconds: int,
) -> dict:
    return {
        "order_no": order_no,
        "category": category,
        "difficulty": difficulty,
        "difficulty_weight": DIFFICULTY_WEIGHT_MAP[difficulty],
        "prompt": prompt,
        "option_a": options[0],
        "option_b": options[1],
        "option_c": options[2],
        "option_d": options[3],
        "correct_option": correct_option,
        "explanation": explanation,
        "tags": ",".join(tags),
        "estimated_seconds": estimated_seconds,
        "is_active": True,
    }


QUESTION_BANK = [
    build_question(
        1,
        "numerical",
        "easy",
        "数列：2，4，8，16，？",
        ["18", "24", "32", "34"],
        "C",
        "每一项都是前一项乘以 2。",
        ["sequence", "doubling"],
        25,
    ),
    build_question(
        2,
        "numerical",
        "easy",
        "一本书原价 120 元，打八折后的价格是？",
        ["84 元", "96 元", "108 元", "112 元"],
        "B",
        "120 × 0.8 = 96。",
        ["discount", "basic-arithmetic"],
        25,
    ),
    build_question(
        3,
        "numerical",
        "medium",
        "数列：3，6，11，18，27，？",
        ["36", "38", "40", "42"],
        "B",
        "相邻差值依次为 3、5、7、9，下一项差值应为 11，所以答案是 38。",
        ["sequence", "difference"],
        35,
    ),
    build_question(
        4,
        "numerical",
        "medium",
        "若 7 台机器 7 分钟生产 7 个零件，那么 21 台机器 21 分钟能生产多少个零件？",
        ["21", "49", "63", "147"],
        "C",
        "每台机器 7 分钟生产 1 个零件，21 分钟生产 3 个，21 台共生产 63 个。",
        ["rate", "proportion"],
        35,
    ),
    build_question(
        5,
        "numerical",
        "medium",
        "某学习小组 5 人测验平均分是 92 分，前 4 人总分是 370 分，第 5 人得了多少分？",
        ["90 分", "92 分", "94 分", "96 分"],
        "A",
        "5 人总分为 5 × 92 = 460，460 - 370 = 90。",
        ["average", "reverse-calculation"],
        35,
    ),
    build_question(
        6,
        "numerical",
        "medium",
        "一件商品先涨价 10%，再降价 10%，最终价格与原价相比如何？",
        ["提高了 1%", "没有变化", "降低了 1%", "降低了 10%"],
        "C",
        "设原价为 100，涨价后为 110，再降价 10% 后为 99，所以比原价低 1%。",
        ["percentage", "compound-change"],
        35,
    ),
    build_question(
        7,
        "numerical",
        "hard",
        "若 a + b = 10，ab = 21，则 a² + b² = ?",
        ["42", "58", "62", "79"],
        "B",
        "a² + b² = (a + b)² - 2ab = 100 - 42 = 58。",
        ["algebra", "identity"],
        45,
    ),
    build_question(
        8,
        "numerical",
        "hard",
        "甲、乙两箱苹果共 54 个。从甲箱取 6 个放入乙箱后，两箱数量相同。原来甲箱有多少个？",
        ["27 个", "30 个", "33 个", "36 个"],
        "C",
        "设甲箱原有 x 个，乙箱原有 y 个，则 x + y = 54，且 x - 6 = y + 6，解得 x = 33。",
        ["equation", "balance"],
        45,
    ),
    build_question(
        9,
        "logical",
        "easy",
        "所有猫都是动物，所有动物都会呼吸。以下哪项一定正确？",
        ["有些动物不是猫", "所有猫都会呼吸", "所有会呼吸的都是猫", "有些猫不会呼吸"],
        "B",
        "根据“猫 ⊂ 动物 ⊂ 会呼吸”，可以推出所有猫都会呼吸。",
        ["syllogism", "deduction"],
        25,
    ),
    build_question(
        10,
        "logical",
        "easy",
        "如果今天下雨，那么地面会湿。现在地面不湿，可以推出什么？",
        ["今天没有下雨", "今天一定刮风", "地面刚被擦干", "无法判断"],
        "A",
        "由“如果 P 则 Q”和“非 Q”可以推出“非 P”。",
        ["modus-tollens", "condition"],
        25,
    ),
    build_question(
        11,
        "logical",
        "medium",
        "甲、乙、丙三人中只有一人说真话。甲说：“乙说真话。”乙说：“丙说假话。”丙说：“甲和乙都说假话。”谁说真话？",
        ["甲", "乙", "丙", "无法确定"],
        "C",
        "逐一假设后可发现，只有“丙说真话”时三句话的真假分布满足题意。",
        ["truth-table", "consistency"],
        35,
    ),
    build_question(
        12,
        "logical",
        "medium",
        "已知命题“如果某人通过考试，那么他完成了复习”为假。以下哪项一定正确？",
        ["有人通过了考试且没有完成复习", "有人没有通过考试但完成了复习", "所有通过考试的人都完成了复习", "没有人完成复习"],
        "A",
        "条件命题 P→Q 为假时，必须满足 P 为真且 Q 为假。",
        ["condition", "false-statement"],
        35,
    ),
    build_question(
        13,
        "logical",
        "medium",
        "四个盒子中只有一个有奖品。甲：奖品不在 1 号。乙：奖品在 2 号。丙：奖品不在 3 号。丁：奖品在 4 号。已知只有一人说真话，奖品在哪个盒子？",
        ["1 号", "2 号", "3 号", "4 号"],
        "D",
        "逐项验证可知，只有奖品在 4 号时，恰好只有丁说真话。",
        ["exclusive-truth", "elimination"],
        35,
    ),
    build_question(
        14,
        "logical",
        "medium",
        "小张、小王、小李三人排队。已知：小张不在最后；小李在小王后面；小王不在最前。三人从前到后的顺序是？",
        ["小张、小王、小李", "小王、小张、小李", "小张、小李、小王", "小李、小张、小王"],
        "A",
        "由“小王不在最前”且“小李在小王后面”可知小王只能在中间，小李在最后，小张在最前。",
        ["ordering", "constraint"],
        35,
    ),
    build_question(
        15,
        "logical",
        "hard",
        "有四张卡片，一面分别写着 A、D、4、7。要检验规则“如果一面是元音字母，那么另一面是偶数”，最少需要翻看哪两张卡片？",
        ["A 和 4", "A 和 7", "D 和 4", "D 和 7"],
        "B",
        "需要检查会使命题失真的两种情况：元音字母这一面，以及奇数这一面，所以是 A 和 7。",
        ["wason-selection", "critical-thinking"],
        45,
    ),
    build_question(
        16,
        "logical",
        "hard",
        "项目规则：如果项目延期，就必须复盘；如果没有复盘，就不能结项。现在某项目已经结项。以下哪项一定为真？",
        ["该项目一定延期了", "该项目做过复盘", "该项目没有延期", "该项目延期且复盘"],
        "B",
        "由“没有复盘就不能结项”可知，既然已经结项，则一定做过复盘。",
        ["chain-reasoning", "contrapositive"],
        45,
    ),
    build_question(
        17,
        "verbal",
        "easy",
        "词语类比：医生 : 医院 = 教师 : ?",
        ["学生", "学校", "黑板", "考试"],
        "B",
        "对应关系是“职业 : 主要工作场所”。",
        ["analogy", "relation"],
        25,
    ),
    build_question(
        18,
        "verbal",
        "easy",
        "选择与“谨慎”最接近的词：",
        ["鲁莽", "审慎", "拖延", "紧张"],
        "B",
        "“谨慎”和“审慎”语义最接近。",
        ["synonym", "vocabulary"],
        25,
    ),
    build_question(
        19,
        "verbal",
        "medium",
        "选择与“稀缺”最接近的词：",
        ["丰富", "昂贵", "罕见", "普通"],
        "C",
        "“稀缺”强调少而不常见，最接近“罕见”。",
        ["synonym", "semantic"],
        35,
    ),
    build_question(
        20,
        "verbal",
        "medium",
        "选出不同类的一项：书籍、报纸、杂志、铅笔。",
        ["书籍", "报纸", "杂志", "铅笔"],
        "D",
        "前三项都是阅读出版物，铅笔属于文具。",
        ["classification", "concept"],
        35,
    ),
    build_question(
        21,
        "verbal",
        "medium",
        "“激励”之于“积极”最接近于：",
        ["惩罚 之于 规矩", "鼓舞 之于 振奋", "拖延 之于 效率", "沉默 之于 表达"],
        "B",
        "“激励”能促成更积极的状态，对应“鼓舞”促成“振奋”。",
        ["analogy", "cause-effect"],
        35,
    ),
    build_question(
        22,
        "verbal",
        "medium",
        "阅读句子：为了让测评结果更可靠，平台会同时参考正确率、题目难度、作答完整度和作答质量。根据这句话，下列哪项最符合原意？",
        ["只要答题速度快就能拿高分", "完整作答比正确率更重要", "平台会综合多个因素判断表现", "百分位等于答对题数"],
        "C",
        "原句强调的是多因素综合判断，而不是只看单一指标。",
        ["reading", "main-idea"],
        35,
    ),
    build_question(
        23,
        "verbal",
        "hard",
        "以下哪个句子中，成语使用最恰当？",
        [
            "面对第一次上台演讲，他依旧从容不迫，紧张得说不出话来。",
            "复盘这次失误时，我们不能浮光掠影，而要逐条分析原因。",
            "这种彩票中奖概率很高，简直可以说是凤毛麟角。",
            "他把作息表写得井井有条，所以房间总是乱成一团。",
        ],
        "B",
        "“浮光掠影”表示观察或处理得很表面，在这里用于提醒不能粗略复盘，语义成立。",
        ["idiom", "context"],
        45,
    ),
    build_question(
        24,
        "verbal",
        "hard",
        "将下列句子按语意排序，最合理的一项是：①因此结果更有解释力 ②平台不再只看单一分数 ③而是同时参考正确率、难度和作答质量 ④新版评分逻辑更强调综合表现",
        ["④②③①", "②④③①", "④③②①", "②③④①"],
        "A",
        "先提出主题“新版评分逻辑更强调综合表现”，再解释“不再只看单一分数”，接着补充“而是同时参考……”，最后得出结果“因此结果更有解释力”。",
        ["sentence-order", "coherence"],
        45,
    ),
    build_question(
        25,
        "spatial",
        "easy",
        "一个 3×3 方阵图案旋转 180° 后，原本位于左上角的元素会移动到哪里？",
        ["左下角", "右上角", "右下角", "中心位置"],
        "C",
        "旋转 180° 后，左上角与右下角互换。",
        ["rotation", "matrix"],
        25,
    ),
    build_question(
        26,
        "spatial",
        "easy",
        "一个图形先顺时针旋转 90°，再做镜像变换。通常最不容易改变的特征是？",
        ["左右位置", "上下位置", "边数与连接关系", "颜色深浅"],
        "C",
        "旋转和镜像会改变方向，但不会改变图形的边数与整体连接关系。",
        ["invariant", "transformation"],
        25,
    ),
    build_question(
        27,
        "spatial",
        "medium",
        "把正方体展开图折回后，若 1 与 6 相对、2 与 5 相对，则 3 与谁相对？",
        ["1", "2", "4", "6"],
        "C",
        "正方体的三组对面一一对应，剩余未配对的是 3 与 4。",
        ["cube", "opposite-face"],
        35,
    ),
    build_question(
        28,
        "spatial",
        "medium",
        "将字母 F 在镜子中左右翻转后，再上下翻转，等价于原图进行多少度旋转？",
        ["90°", "180°", "270°", "无法等价"],
        "B",
        "左右翻转再上下翻转，整体效果等价于旋转 180°。",
        ["mirror", "rotation"],
        35,
    ),
    build_question(
        29,
        "spatial",
        "medium",
        "将一个三角形沿高线对折后，如果两腰能够完全重合，这个三角形最可能是：",
        ["直角三角形", "等腰三角形", "任意三角形", "钝角三角形"],
        "B",
        "沿高线对折后两腰重合，说明该高线同时是对称轴，符合等腰三角形特征。",
        ["symmetry", "triangle"],
        35,
    ),
    build_question(
        30,
        "spatial",
        "medium",
        "一个箭头先向右旋转 90°，再做上下翻转，最终箭头指向哪里？",
        ["上", "下", "左", "右"],
        "A",
        "向右的箭头顺时针旋转 90° 变成向下，再做上下翻转后变成向上。",
        ["orientation", "transformation"],
        35,
    ),
    build_question(
        31,
        "spatial",
        "hard",
        "在一个 2×2 方格中，黑块位于左上角。若图形先左右镜像，再顺时针旋转 90°，黑块最终位于哪里？",
        ["左上角", "右上角", "左下角", "右下角"],
        "D",
        "左右镜像后黑块到右上角，再顺时针旋转 90° 后移动到右下角。",
        ["grid", "multi-step"],
        45,
    ),
    build_question(
        32,
        "spatial",
        "hard",
        "由 8 个相同小正方体拼成一个 2×2×2 的大立方体。这个大立方体表面一共能看到多少个小正方形面？",
        ["12", "16", "24", "32"],
        "C",
        "大立方体共有 6 个面，每个面由 2×2 = 4 个小正方形组成，因此总数为 24。",
        ["solid", "counting"],
        45,
    ),
]
