QUESTION_BANK = [
    {
        "order_no": 1,
        "category": "numerical",
        "difficulty": 1,
        "prompt": "数列：2, 4, 8, 16, ?",
        "option_a": "18",
        "option_b": "24",
        "option_c": "32",
        "option_d": "34",
        "correct_option": "C",
        "explanation": "每一项都是前一项乘以 2。",
    },
    {
        "order_no": 2,
        "category": "logical",
        "difficulty": 1,
        "prompt": "所有猫都是动物，所有动物都会呼吸。以下哪项一定正确？",
        "option_a": "有些动物不是猫",
        "option_b": "所有猫都会呼吸",
        "option_c": "所有会呼吸的都是猫",
        "option_d": "有些猫不会呼吸",
        "correct_option": "B",
        "explanation": "三段论推理：猫 ⊂ 动物 ⊂ 会呼吸，因此所有猫都会呼吸。",
    },
    {
        "order_no": 3,
        "category": "verbal",
        "difficulty": 1,
        "prompt": "词语类比：医生 : 医院 = 教师 : ?",
        "option_a": "学生",
        "option_b": "学校",
        "option_c": "黑板",
        "option_d": "考试",
        "correct_option": "B",
        "explanation": "对应关系是“职业 : 主要工作场所”。",
    },
    {
        "order_no": 4,
        "category": "spatial",
        "difficulty": 2,
        "prompt": "把正方体展开图折回后，相对的两个面不可能相邻。若 1 与 6 相对，2 与 5 相对，则 3 与谁相对？",
        "option_a": "1",
        "option_b": "2",
        "option_c": "4",
        "option_d": "6",
        "correct_option": "C",
        "explanation": "正方体 3 组对面一一对应，剩余未配对的是 3 与 4。",
    },
    {
        "order_no": 5,
        "category": "numerical",
        "difficulty": 2,
        "prompt": "若 7 台机器 7 分钟生产 7 个零件，那么 21 台机器 21 分钟生产多少个零件？",
        "option_a": "21",
        "option_b": "49",
        "option_c": "63",
        "option_d": "147",
        "correct_option": "C",
        "explanation": "每台机器 7 分钟产 1 个，21 分钟产 3 个；21 台共 63 个。",
    },
    {
        "order_no": 6,
        "category": "logical",
        "difficulty": 2,
        "prompt": "甲、乙、丙三人中只有一人说真话。甲说：‘乙说真话。’乙说：‘丙说假话。’丙说：‘甲和乙都说假话。’谁说真话？",
        "option_a": "甲",
        "option_b": "乙",
        "option_c": "丙",
        "option_d": "无法确定",
        "correct_option": "C",
        "explanation": "枚举可知仅丙为真时成立。",
    },
    {
        "order_no": 7,
        "category": "verbal",
        "difficulty": 2,
        "prompt": "选择与“谨慎”最接近的词：",
        "option_a": "鲁莽",
        "option_b": "审慎",
        "option_c": "拖延",
        "option_d": "紧张",
        "correct_option": "B",
        "explanation": "“谨慎”与“审慎”最接近。",
    },
    {
        "order_no": 8,
        "category": "spatial",
        "difficulty": 2,
        "prompt": "一个图形顺时针旋转 90° 再镜像，最关键的不变量通常是？",
        "option_a": "左右位置",
        "option_b": "上下位置",
        "option_c": "边数与连接关系",
        "option_d": "颜色深浅",
        "correct_option": "C",
        "explanation": "旋转和镜像会改变方向，但不会改变边数和拓扑连接关系。",
    },
    {
        "order_no": 9,
        "category": "numerical",
        "difficulty": 2,
        "prompt": "数列：3, 6, 11, 18, 27, ?",
        "option_a": "36",
        "option_b": "38",
        "option_c": "40",
        "option_d": "42",
        "correct_option": "B",
        "explanation": "差值分别为 3, 5, 7, 9，所以下一个差值为 11，答案 27+11=38。",
    },
    {
        "order_no": 10,
        "category": "logical",
        "difficulty": 2,
        "prompt": "已知‘如果某人通过考试，那么他完成了复习’为假。以下哪项一定正确？",
        "option_a": "有人通过了考试且没有完成复习",
        "option_b": "有人没有通过考试但完成了复习",
        "option_c": "所有通过考试的人都完成了复习",
        "option_d": "没有人完成复习",
        "correct_option": "A",
        "explanation": "条件命题 P→Q 为假时，必须满足 P 真且 Q 假。",
    },
    {
        "order_no": 11,
        "category": "verbal",
        "difficulty": 2,
        "prompt": "“稀缺”与下列哪一项关系最接近“珍贵”？",
        "option_a": "丰富",
        "option_b": "昂贵",
        "option_c": "罕见",
        "option_d": "普通",
        "correct_option": "C",
        "explanation": "“稀缺”最接近“罕见”。",
    },
    {
        "order_no": 12,
        "category": "spatial",
        "difficulty": 3,
        "prompt": "将字母 F 在镜子中左右反转后，再上下翻转，等价于原图进行多少度旋转？",
        "option_a": "90°",
        "option_b": "180°",
        "option_c": "270°",
        "option_d": "无法等价",
        "correct_option": "B",
        "explanation": "左右反转再上下翻转等价于 180° 旋转。",
    },
    {
        "order_no": 13,
        "category": "numerical",
        "difficulty": 3,
        "prompt": "若 a+b=10，ab=21，则 a²+b² = ?",
        "option_a": "42",
        "option_b": "58",
        "option_c": "62",
        "option_d": "79",
        "correct_option": "B",
        "explanation": "a²+b²=(a+b)²-2ab=100-42=58。",
    },
    {
        "order_no": 14,
        "category": "logical",
        "difficulty": 3,
        "prompt": "四个盒子中只有一个有奖品。甲：奖品不在1号。乙：奖品在2号。丙：奖品不在2号。丁：奖品在4号。已知只有一人说真话，奖品在哪个盒子？",
        "option_a": "1号",
        "option_b": "2号",
        "option_c": "3号",
        "option_d": "4号",
        "correct_option": "D",
        "explanation": "逐项验证，只有在 4 号时仅丁说真话。",
    },
    {
        "order_no": 15,
        "category": "verbal",
        "difficulty": 3,
        "prompt": "选择不同类的一项：书籍、报纸、杂志、铅笔",
        "option_a": "书籍",
        "option_b": "报纸",
        "option_c": "杂志",
        "option_d": "铅笔",
        "correct_option": "D",
        "explanation": "前三项都是阅读出版物，铅笔是文具。",
    },
    {
        "order_no": 16,
        "category": "spatial",
        "difficulty": 3,
        "prompt": "一个 3×3 方阵图案顺时针旋转 180° 后，位于左上角的元素会移动到哪里？",
        "option_a": "左下角",
        "option_b": "右上角",
        "option_c": "右下角",
        "option_d": "中心",
        "correct_option": "C",
        "explanation": "180° 旋转后左上角到右下角。",
    },
    {
        "order_no": 17,
        "category": "numerical",
        "difficulty": 3,
        "prompt": "某项任务甲单独做 6 小时完成，乙单独做 3 小时完成，两人合作 1 小时后还剩多少？",
        "option_a": "1/6",
        "option_b": "1/3",
        "option_c": "1/2",
        "option_d": "2/3",
        "correct_option": "C",
        "explanation": "甲效率 1/6，乙效率 1/3，合作 1/2，做 1 小时完成 1/2，还剩 1/2。",
    },
    {
        "order_no": 18,
        "category": "logical",
        "difficulty": 3,
        "prompt": "若有些程序员会画画，所有会画画的人都喜欢观察，则下列哪项一定为真？",
        "option_a": "所有程序员都喜欢观察",
        "option_b": "有些程序员喜欢观察",
        "option_c": "有些喜欢观察的人不是程序员",
        "option_d": "没有程序员不喜欢观察",
        "correct_option": "B",
        "explanation": "由“有些程序员会画画”与“所有会画画的人都喜欢观察”推出。",
    },
    {
        "order_no": 19,
        "category": "verbal",
        "difficulty": 3,
        "prompt": "‘激励’之于‘积极’最接近于：",
        "option_a": "惩罚 之于 规矩",
        "option_b": "鼓舞 之于 振奋",
        "option_c": "拖延 之于 效率",
        "option_d": "沉默 之于 表达",
        "correct_option": "B",
        "explanation": "两者都是促进正向状态的近义作用关系。",
    },
    {
        "order_no": 20,
        "category": "spatial",
        "difficulty": 3,
        "prompt": "将一个三角形沿高线对折，两腰重合。这个三角形最可能是：",
        "option_a": "直角三角形",
        "option_b": "等腰三角形",
        "option_c": "任意三角形",
        "option_d": "钝角三角形",
        "correct_option": "B",
        "explanation": "沿对称轴对折后两腰重合，这是等腰三角形特征。",
    },
]
